### ISSUE TITLE
Webmin login doesn't work after moving to /webmin sub-path

### ISSUE THREAD

**Issue by benjamink** [PiSCSI/piscsi#1380] opened 2023-11-18 16:05 UTC
After the change in #1354 the Webmin authentication no longer works.  Any attempts to login with the `pi` user (or any other user) are just redirected back to the Webmin login page.  The `root` user login will work if you use the Webmin command to generate a local `root` user password: 

```
/usr/share/webmin/changepass.pl /etc/webmin root <password>
```

But this isn't the desired behavior.  Webmin should allow any users with `sudo` permissions to login as Webmin admins automatically (this is how it used to work).  Something about moving Webmin to the `/webmin` sub-path under Nginx is breaking things.

**Comment by benjamink** [comment] 2023-11-18 16:07
Adding some configuration guides for reference.  I've tried these changes & they still don't work: 

https://webmin.com/faq/#can-i-run-webmin-or-usermin-behind-reverse-proxy

https://superuser.com/a/1709050

**Comment by rdmark** [comment] 2023-11-20 00:13
@benjamink Have you tried asking for advice at the Virtualmin forums? https://forum.virtualmin.com/

**Comment by rdmark** [comment] 2023-11-20 04:03
The mother ticket is here: https://github.com/PiSCSI/piscsi/issues/1351

Closing since the regression bug has been fixed

**Closed by rdmark** 2023-11-20 04:03 UTC
Labels: bug
